import { prisma } from "@repo/database";

// xStocks (Backed Finance) — decimals: 8 (verified on-chain for AAPLx, TSLAx)
const XSTOCKS: Array<{ symbol: string; name: string; mint: string }> = [
  { symbol: "ABTx", name: "Abbott Laboratories xStock", mint: "XsHtf5RpxsQ7jeJ9ivNewouZKJHbPxhPoEy6yYvULr7" },
  { symbol: "ABBVx", name: "AbbVie xStock", mint: "XswbinNKyPmzTa5CskMbCPvMW6G5CMnZXZEeQSSQoie" },
  { symbol: "ACNx", name: "Accenture xStock", mint: "Xs5UJzmCRQ8DWZjskExdSQDnbE6iLkRu2jjrRAB1JSU" },
  { symbol: "AAPLx", name: "Apple xStock", mint: "XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp" },
  { symbol: "AMBRx", name: "Amber xStock", mint: "XsaQTCgebC2KPbf27KUhdv5JFvHhQ4GDAPURwrEhAzb" },
  { symbol: "AMZNx", name: "Amazon xStock", mint: "Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg" },
  { symbol: "APPx", name: "AppLovin xStock", mint: "XsPdAVBi8Zc1xvv53k4JcMrQaEDTgkGqKYeh7AYgPHV" },
  { symbol: "AVGOx", name: "Broadcom xStock", mint: "XsgSaSvNSqLTtFuyWPBhK9196Xb9Bbdyjj4fH3cPJGo" },
  { symbol: "AZNx", name: "AstraZeneca xStock", mint: "Xs3ZFkPYT2BN7qBMqf1j1bfTeTm1rFzEFSsQ1z3wAKU" },
  { symbol: "BACx", name: "Bank of America xStock", mint: "XswsQk4duEQmCbGzfqUUWYmi7pV7xpJ9eEmLHXCaEQP" },
  { symbol: "BRK.Bx", name: "Berkshire Hathaway B xStock", mint: "Xs6B6zawENwAbWVi7w92rjazLuAr5Az59qgWKcNb45x" },
  { symbol: "CMCSAx", name: "Comcast xStock", mint: "XsvKCaNsxg2GN8jjUmq71qukMJr7Q1c5R2Mk9P8kcS8" },
  { symbol: "COINx", name: "Coinbase xStock", mint: "Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu" },
  { symbol: "CRCLx", name: "Circle xStock", mint: "XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1" },
  { symbol: "CRMx", name: "Salesforce xStock", mint: "XsczbcQ3zfcgAEt9qHQES8pxKAVG5rujPSHQEXi4kaN" },
  { symbol: "CRWDx", name: "CrowdStrike xStock", mint: "Xs7xXqkcK7K8urEqGg52SECi79dRp2cEKKuYjUePYDw" },
  { symbol: "CSCOx", name: "Cisco xStock", mint: "Xsr3pdLQyXvDJBFgpR5nexCEZwXvigb8wbPYp4YoNFf" },
  { symbol: "CVXx", name: "Chevron xStock", mint: "XsNNMt7WTNA2sV3jrb1NNfNgapxRF5i4i6GcnTRRHts" },
  { symbol: "DFDVx", name: "DFDV xStock", mint: "Xs2yquAgsHByNzx68WJC55WHjHBvG9JsMB7CWjTLyPy" },
  { symbol: "DHRx", name: "Danaher xStock", mint: "Xseo8tgCZfkHxWS9xbFYeKFyMSbWEvZGFV1Gh53GtCV" },
  { symbol: "GLDx", name: "SPDR Gold Shares xStock", mint: "Xsv9hRk1z5ystj9MhnA7Lq4vjSsLwzL2nxrwmwtD3re" },
  { symbol: "GMEx", name: "GameStop xStock", mint: "Xsf9mBktVB9BSU5kf4nHxPq5hCBJ2j2ui3ecFGxPRGc" },
  { symbol: "GOOGLx", name: "Alphabet xStock", mint: "XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN" },
  { symbol: "GSx", name: "Goldman Sachs xStock", mint: "XsgaUyp4jd1fNBCxgtTKkW64xnnhQcvgaxzsbAq5ZD1" },
  { symbol: "HDx", name: "Home Depot xStock", mint: "XszjVtyhowGjSC5odCqBpW1CtXXwXjYokymrk7fGKD3" },
  { symbol: "HONx", name: "Honeywell xStock", mint: "XsRbLZthfABAPAfumWNEJhPyiKDW6TvDVeAeW7oKqA2" },
  { symbol: "HOODx", name: "Robinhood xStock", mint: "XsvNBAYkrDRNhA7wPHQfX3ZUXZyZLdnCQDfHZ56bzpg" },
  { symbol: "IBMx", name: "IBM xStock", mint: "XspwhyYPdWVM8XBHZnpS9hgyag9MKjLRyE3tVfmCbSr" },
  { symbol: "INTCx", name: "Intel xStock", mint: "XshPgPdXFRWB8tP1j82rebb2Q9rPgGX37RuqzohmArM" },
  { symbol: "JNJx", name: "Johnson & Johnson xStock", mint: "XsGVi5eo1Dh2zUpic4qACcjuWGjNv8GCt3dm5XcX6Dn" },
  { symbol: "JPMx", name: "JPMorgan Chase xStock", mint: "XsMAqkcKsUewDrzVkait4e5u4y8REgtyS7jWgCpLV2C" },
  { symbol: "KOx", name: "Coca-Cola xStock", mint: "XsaBXg8dU5cPM6ehmVctMkVqoiRG2ZjMo1cyBJ3AykQ" },
  { symbol: "LINx", name: "Linde xStock", mint: "XsSr8anD1hkvNMu8XQiVcmiaTP7XGvYu7Q58LdmtE8Z" },
  { symbol: "LLYx", name: "Eli Lilly xStock", mint: "Xsnuv4omNoHozR6EEW5mXkw8Nrny5rB3jVfLqi6gKMH" },
  { symbol: "MAx", name: "Mastercard xStock", mint: "XsApJFV9MAktqnAc6jqzsHVujxkGm9xcSUffaBoYLKC" },
  { symbol: "MCDx", name: "McDonald's xStock", mint: "XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2" },
  { symbol: "MDTx", name: "Medtronic xStock", mint: "XsDgw22qRLTv5Uwuzn6T63cW69exG41T6gwQhEK22u2" },
  { symbol: "METAx", name: "Meta Platforms xStock", mint: "Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu" },
  { symbol: "MRKx", name: "Merck xStock", mint: "XsnQnU7AdbRZYe2akqqpibDdXjkieGFfSkbkjX1Sd1X" },
  { symbol: "MRVLx", name: "Marvell Technology xStock", mint: "XsuxRGDzbLjnJ72v74b7p9VY6N66uYgTCyfwwRjVCJA" },
  { symbol: "MSFTx", name: "Microsoft xStock", mint: "XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX" },
  { symbol: "MSTRx", name: "MicroStrategy xStock", mint: "XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ" },
  { symbol: "NFLXx", name: "Netflix xStock", mint: "XsEH7wWfJJu2ZT3UCFeVfALnVA6CP5ur7Ee11KmzVpL" },
  { symbol: "NVDAx", name: "NVIDIA xStock", mint: "Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh" },
  { symbol: "NVOx", name: "Novo Nordisk xStock", mint: "XsfAzPzYrYjd4Dpa9BU3cusBsvWfVB9gBcyGC87S57n" },
  { symbol: "OPENx", name: "Opendoor xStock", mint: "XsGtpmjhmC8kyjVSWL4VicGu36ceq9u55PTgF8bhGv6" },
  { symbol: "ORCLx", name: "Oracle xStock", mint: "XsjFwUPiLofddX5cWFHW35GCbXcSu1BCUGfxoQAQjeL" },
  { symbol: "PEPx", name: "PepsiCo xStock", mint: "Xsv99frTRUeornyvCfvhnDesQDWuvns1M852Pez91vF" },
  { symbol: "PFEx", name: "Pfizer xStock", mint: "XsAtbqkAP1HJxy7hFDeq7ok6yM43DQ9mQ1Rh861X8rw" },
  { symbol: "PGx", name: "Procter & Gamble xStock", mint: "XsYdjDjNUygZ7yGKfQaB6TxLh2gC6RRjzLtLAGJrhzV" },
  { symbol: "PLTRx", name: "Palantir xStock", mint: "XsoBhf2ufR8fTyNSjqfU71DYGaE6Z3SUGAidpzriAA4" },
  { symbol: "PMx", name: "Philip Morris xStock", mint: "Xsba6tUnSjDae2VcopDB6FGGDaxRrewFCDa5hKn5vT3" },
  { symbol: "QQQx", name: "Nasdaq-100 ETF xStock", mint: "Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ" },
  { symbol: "SPYx", name: "S&P 500 ETF xStock", mint: "XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W" },
  { symbol: "TBLLx", name: "US Treasury Bill ETF xStock", mint: "XsqBC5tcVQLYt8wqGCHRnAUUecbRYXoJCReD6w7QEKp" },
  { symbol: "TMOx", name: "Thermo Fisher Scientific xStock", mint: "Xs8drBWy3Sd5QY3aifG9kt9KFs2K3PGZmx7jWrsrk57" },
  { symbol: "TQQQx", name: "ProShares UltraPro QQQ xStock", mint: "XsjQP3iMAaQ3kQScQKthQpx9ALRbjKAjQtHg6TFomoc" },
  { symbol: "TSLAx", name: "Tesla xStock", mint: "XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB" },
  { symbol: "UNHx", name: "UnitedHealth xStock", mint: "XszvaiXGPwvk2nwb3o9C1CX4K6zH8sez11E6uyup6fe" },
  { symbol: "Vx", name: "Visa xStock", mint: "XsqgsbXwWogGJsNcVZ3TyVouy2MbTkfCFhCGGGcQZ2p" },
  { symbol: "VTIx", name: "Vanguard Total Stock Market xStock", mint: "XsssYEQjzxBCFgvYFFNuhJFBeHNdLWYeUSP8F45cDr9" },
  { symbol: "WMTx", name: "Walmart xStock", mint: "Xs151QeqTCiuKtinzfRATnUESM2xTU6V9Wy8Vy538ci" },
  { symbol: "XOMx", name: "Exxon Mobil xStock", mint: "XsaHND8sHyfMfsWPj6kSdd5VwvCayZvjYgKmmcNL5qh" },
];

// Ondo GM tokens — decimals: 9 (verified from Jupiter API)
const ONDO_TOKENS: Array<{ symbol: string; name: string; mint: string }> = [
  { symbol: "AALon", name: "American Airlines (Ondo)", mint: "9wYZetvT8J2ptfsRca5gzLBGvcUug38mp9yT3xaondo" },
  { symbol: "AAPLon", name: "Apple (Ondo)", mint: "123mYEnRLM2LLYsJW3K6oyYh8uP1fngj732iG638ondo" },
  { symbol: "ABBVon", name: "AbbVie (Ondo)", mint: "MFerpBVGKZh2jXN7cbJdXRXQTp6j6pbSnSZrfWrondo" },
  { symbol: "ABNBon", name: "Airbnb (Ondo)", mint: "128qNYovdGv2YqayErcJgU7gDwbNVX1VuoxbtWz8ondo" },
  { symbol: "ABTon", name: "Abbott (Ondo)", mint: "129gRoHKhVg7CvPMrqVsEB4uYZo6zV4yDZX6NBg9ondo" },
  { symbol: "ACHRon", name: "Archer Aviation (Ondo)", mint: "KcCVQxG9LhFYP5o9DWFKTFgFShPPQkDEemVbiFyondo" },
  { symbol: "ACNon", name: "Accenture (Ondo)", mint: "12LxMMJYVSf4LoeqjFE47BQQNRciaH9E3nbDfjH4ondo" },
  { symbol: "ADBEon", name: "Adobe (Ondo)", mint: "12Rh6JhfW4X5fKP16bbUdb4pcVCKDHFB48x8GG33ondo" },
  { symbol: "ADIon", name: "Analog Devices (Ondo)", mint: "LmTMwmZLNZszn3qpjmnbhfP12U4qWDivaEBwSBSondo" },
  { symbol: "AGGon", name: "iShares US Aggregate Bond ETF (Ondo)", mint: "13qTjKx53y6LKGGStiKeieGbnVx3fx1bbwopKFb3ondo" },
  { symbol: "AMATon", name: "Applied Materials (Ondo)", mint: "7eRX747PSbVtGVx3qD5UFdkNM2BfTy86ikUiCMhondo" },
  { symbol: "AMCon", name: "AMC Entertainment (Ondo)", mint: "C9xNaNujcF1a5fidWAAFReFYqhLRVbyk4yPyGqzondo" },
  { symbol: "AMDon", name: "AMD (Ondo)", mint: "14diAn5z8kjrKwSC8WLqvBqqe5YmihJhjxRxd8Z6ondo" },
  { symbol: "AMGNon", name: "Amgen (Ondo)", mint: "SS6AEWhzRrxhL2cXzKKjhFt3rCzmHHGKmFyugDTondo" },
  { symbol: "AMZNon", name: "Amazon (Ondo)", mint: "14Tqdo8V1FhzKsE3W2pFsZCzYPQxxupXRcqw9jv6ondo" },
  { symbol: "ANETon", name: "Arista Networks (Ondo)", mint: "Cq6QtvHpXbJWtFaiMhUDtHy8YVZ95gcD1oZ1cohondo" },
  { symbol: "APOon", name: "Apollo Global Management (Ondo)", mint: "14VXAhoa1R74vi1ZuiQyGLJrnDMfoFBPJSCpGVz3ondo" },
  { symbol: "APPon", name: "AppLovin (Ondo)", mint: "14Z8rQQe2Aza33YgEUmj3g3QGNz8DXLiFPuCnsD1ondo" },
  { symbol: "ARMon", name: "Arm Holdings (Ondo)", mint: "15SsCZqCsM9fZGhTmP4rdJTPT9WGZKazDSsgeQ8ondo" },
  { symbol: "ASMLon", name: "ASML Holding (Ondo)", mint: "1eLZPRsn8bAKmoxsqDMH9Q2m2k7GMNp6RLSQGm8ondo" },
  { symbol: "AVGOon", name: "Broadcom (Ondo)", mint: "1FWZtdWN7y38BSXGzbs8D6Shk88oL9atDNgbVz9ondo" },
  { symbol: "AXPon", name: "American Express (Ondo)", mint: "1WxT6NdK7uqpfXuKpALxL2n3f7Rq61XXeHA8UM4ondo" },
  { symbol: "BABAon", name: "Alibaba (Ondo)", mint: "1zvb9ELBFShBCWKEk5jRTJAaPAwtVt7quEXx1X4ondo" },
  { symbol: "BACon", name: "Bank of America (Ondo)", mint: "Wk8gC6iTNp8dqd4ghkJ3h1giiUnyhykwHh7tYWjondo" },
  { symbol: "BAon", name: "Boeing (Ondo)", mint: "1YVZ4LGpq8CAhpdpm3mgy7GgPb83gJczCpxLUQ3ondo" },
  { symbol: "BBAIon", name: "BigBear.ai (Ondo)", mint: "YXE7mph6XhsgnyezkMEcTuohSuWhbLWfwx2Hh6mondo" },
  { symbol: "BIDUon", name: "Baidu (Ondo)", mint: "54CoRF2FYMZNJg9tS36xq5BUcLZ7rju1r59jGc2ondo" },
  { symbol: "BILIon", name: "Bilibili (Ondo)", mint: "14kLsQVmc64qZexYuR4XGop9y8BeMkd77pJUm1Rhondo" },
  { symbol: "BINCon", name: "iShares Flexible Income ETF (Ondo)", mint: "mhZ69E1vDnAsQJXAwarLYSX5tmgeMajXBJ2rXAcondo" },
  { symbol: "BLKon", name: "Blackrock (Ondo)", mint: "5H1VpMzRuoNtRbPTRCz35ETtEUtnkt8hJuQb9v7ondo" },
  { symbol: "BLSHon", name: "Bullish (Ondo)", mint: "A9PFmw9Hu8zzxDUoU351pio1E1XWBWBfWnjT9qoondo" },
  { symbol: "BMNRon", name: "BitMine (Ondo)", mint: "MYXqkDYbzr7vjXAz2BapR4AiYRXzoikGirrLoRzondo" },
  { symbol: "BTGOon", name: "BitGo (Ondo)", mint: "bgJWGuQxyoyFeXwzYZKBmoujVdatGFYPNFnv1a6ondo" },
  { symbol: "BTGon", name: "B2Gold (Ondo)", mint: "cBnVXDyZgaaLZM18wAmqsUKnRUFAEJWbq6VuUoaondo" },
  { symbol: "BZon", name: "Kanzhun (Ondo)", mint: "doPqjCxi6UkANkvMz5fSuYGEo5PGppVpTZMeB5vondo" },
  { symbol: "CATon", name: "Caterpillar (Ondo)", mint: "AErxJJxGbc9cZzZoZepN62BNfg5RXns8tmEc3Zpondo" },
  { symbol: "CEGon", name: "Constellation Energy (Ondo)", mint: "7NWHifsBnn9DimUeNnsHdEXkTZhXmJTiXxcCngBondo" },
  { symbol: "CIFRon", name: "Cipher Mining (Ondo)", mint: "WNZBSkNBNP3Ct1pcFn6Fu4sZQFhnu48EsM9voCEondo" },
  { symbol: "CLOAon", name: "iShares AAA CLO ETF (Ondo)", mint: "t71FyTYHVkPAb5g48adDHmkVxXYbUuP2eq6jDZLondo" },
  { symbol: "CLOIon", name: "VanEck CLO ETF (Ondo)", mint: "ucQ3VfWAx9pkCN4Kg84zE56FtB4FJN2kQH4ArYYondo" },
  { symbol: "CMGon", name: "Chipotle (Ondo)", mint: "5owVsVFSHACQuippFYdLp3qWRobp2EGcwxMmsr6ondo" },
  { symbol: "COFon", name: "Capital One (Ondo)", mint: "R2uDbMtmHq5xSS5SserrovdRKdpiqnVBCd2AHLhondo" },
  { symbol: "COINon", name: "Coinbase (Ondo)", mint: "5u6KDiNJXxX4rGMfYT4BApZQC5CuDNrG6MHkwp1ondo" },
  { symbol: "COPXon", name: "Global X Copper Miners ETF (Ondo)", mint: "X7j77hTmjZJbepkXXBcsEapM8qNgdfihkFj6CZ5ondo" },
  { symbol: "COPon", name: "ConocoPhillips (Ondo)", mint: "X68p9qTpEMkR1TLpXUP2ZJo8PG4Qge2Y2ZLdjA2ondo" },
  { symbol: "COSTon", name: "Costco (Ondo)", mint: "6btaz134wjHkR8sqhAYrtSM6tavftfxnRvnyMd8ondo" },
  { symbol: "CPNGon", name: "Coupang (Ondo)", mint: "NKyzy31w2J7odLb2CW3Ft4fpKXkW3LBt1pvpkVLondo" },
  { symbol: "CRCLon", name: "Circle (Ondo)", mint: "6xHEyem9hmkGtVq6XGCiQUGpPsHBaoYuYdFNZa5ondo" },
  { symbol: "CRMon", name: "Salesforce (Ondo)", mint: "7D7ukbcnUNYt7Et5vtsDZhAy28MKu9pkHka1Hp9ondo" },
  { symbol: "CRWDon", name: "CrowdStrike (Ondo)", mint: "cdKfoNjbXgnSuxvoajhtH3uixfZhq1YXhQsS1Rwondo" },
  { symbol: "CSCOon", name: "Cisco (Ondo)", mint: "7DWcZE1uVc8m2mf9pV8KNov28ET7HsvHkhrhgr9ondo" },
  { symbol: "CVNAon", name: "Carvana (Ondo)", mint: "FGmUDXqA3AbWfo5b3NUcsvwoUFCF4tr9ea6uercondo" },
  { symbol: "CVXon", name: "Chevron (Ondo)", mint: "7tgKziACteG26VjV5xKufojKxwTgCFyTwmWUmz5ondo" },
  { symbol: "Con", name: "Citigroup (Ondo)", mint: "PjtfUiw6Hwd8PZ94EcUw8mBSYxp7SjjzSLeNTDKondo" },
  { symbol: "DASHon", name: "DoorDash (Ondo)", mint: "83P1gCFBZfGRCwJuBt9juxJKEsZwejJoG66eTZ6ondo" },
  { symbol: "DBCon", name: "Invesco DB Commodity ETF (Ondo)", mint: "td1aY5AvYQuwGD75qNq9aPipMexraN9mQXJwqifondo" },
  { symbol: "DEon", name: "Deere (Ondo)", mint: "CqQyAZjB9LGFTG95eiadGTkfhd9QA12ProeKsQmondo" },
  { symbol: "DGRWon", name: "WisdomTree US Quality Dividend Growth Fund (Ondo)", mint: "gnoSQSNTNZHViqVfxCcPDVxcRA29mrJL7C6JqYLondo" },
  { symbol: "DISon", name: "Disney (Ondo)", mint: "mJf1xT3suXtkXBCfZcE9oUUuyxkvSgqYBWiX7v1ondo" },
  { symbol: "DNNon", name: "Denison Mines (Ondo)", mint: "12J2LD3tuLfdiVKnWZMHRMrbnXDY9rM4yqVLUa5yondo" },
  { symbol: "EEMon", name: "iShares MSCI Emerging Markets ETF (Ondo)", mint: "916SDKz7y5ZcEZC9CtnQ5Djs1Y8Yv3UAPb6bak8ondo" },
  { symbol: "EFAon", name: "iShares MSCI EAFE ETF (Ondo)", mint: "AbvryMGnaba9oADMZk8Vp2Av6MtczsncGyfWaC4ondo" },
  { symbol: "EQIXon", name: "Equinix (Ondo)", mint: "aheEdmuryJU8ymy8LjYheZH5i2BW1UMsfuWQKD2ondo" },
  { symbol: "FIGRon", name: "Figure Technology Solutions (Ondo)", mint: "ZmHxc6Gt27RJKxD2ay6UL4n9yQ7mKAq4XZQUeVhondo" },
  { symbol: "FIGon", name: "Figma (Ondo)", mint: "aLDdFsr3VTUQaHFK6yNvQxztvxQ8nxW4AMuSGC7ondo" },
  { symbol: "FTGCon", name: "First Trust Global Tactical Commodity Fund (Ondo)", mint: "ivBnfPTyuHDNWmMSnbavckhJK6SHZW8h77nZKsEondo" },
  { symbol: "FUTUon", name: "Futu Holdings (Ondo)", mint: "Ao5rKFRQ54W3DKSAtqfhBRPNHewwWRLNLao2JL9ondo" },
  { symbol: "Fon", name: "Ford Motor (Ondo)", mint: "5hT2o25X9tGXipwhLckaUdgnxrZ6Y8eiUwdhpLeondo" },
  { symbol: "GEMIon", name: "Gemini Space Station (Ondo)", mint: "NrTdGMA3ujUvWXkwXyZKnhoByb32KTjRh5Vo47yondo" },
  { symbol: "GEon", name: "General Electric (Ondo)", mint: "aTBfDuLRqYHBiG82bHA7DzwjSDTFre2dRtGH3S5ondo" },
  { symbol: "GLDon", name: "SPDR Gold Shares (Ondo)", mint: "hWfiw4mcxT8rnNFkk6fsCQSxoxgZ9yVhB6tyeVcondo" },
  { symbol: "GMEon", name: "GameStop (Ondo)", mint: "aznKt8v32CwYMEcTcB4bGTv8DXWStCpHrcCtyy7ondo" },
  { symbol: "GOOGLon", name: "Alphabet (Ondo)", mint: "bbahNA5vT9WJeYft8tALrH1LXWffjwqVoUbqYa1ondo" },
  { symbol: "GRABon", name: "Grab Holdings (Ondo)", mint: "m9GcsVgdjaL3KsdtSFHimnhtsUMpTHkjtwEG4Tzondo" },
  { symbol: "GRNDon", name: "Grindr (Ondo)", mint: "Gc1aT3ay7FXL3qdAW7cNSXYPDsGavy7qiACuxwxondo" },
  { symbol: "GSon", name: "Goldman Sachs (Ondo)", mint: "BchJRy2snmhJZf3rQ9LJ3ePs2BGfYgfvQNo31d2ondo" },
  { symbol: "HDon", name: "Home Depot (Ondo)", mint: "MtEXKVN3Pcggy8MPA3eJr15H6SK3RXheScqj9qtondo" },
  { symbol: "HIMSon", name: "Hims & Hers Health (Ondo)", mint: "bdh3njeo19d2TBLAKTGvCWdSoArfVw8uZBAJHY4ondo" },
  { symbol: "HOODon", name: "Robinhood (Ondo)", mint: "BVdXGvmgi6A9oAiwWvBvP76fyTqcCNRJMM7zMN6ondo" },
  { symbol: "HYGon", name: "iBoxx High Yield Corporate Bond ETF (Ondo)", mint: "c5ug15fwZRfQhhVa6LHscFY33ebVDHcVCezYpj7ondo" },
  { symbol: "IAUon", name: "iShares Gold Trust (Ondo)", mint: "M77ZvkZ8zW5udRbuJCbuwSwavRa7bGAZYMTwru8ondo" },
  { symbol: "IBMon", name: "IBM (Ondo)", mint: "C8bZkgSxXkyT1RgxByp2teJ24hgimPLoyEYoNa9ondo" },
  { symbol: "IEFAon", name: "iShares Core MSCI EAFE ETF (Ondo)", mint: "C9J9vZ8N79GzzxFoRkPWCkGtMKU8akg4FhUk4r9ondo" },
  { symbol: "IEMGon", name: "iShares Core MSCI Emerging Markets ETF (Ondo)", mint: "cdVNL7wK8mf1UCDqM6zdrziRv4hmvqWhXeTcck2ondo" },
  { symbol: "IJHon", name: "iShares Core S&P MidCap ETF (Ondo)", mint: "cfPLN9WXD2BTkbZhRZMVXPmVSiRo44hJWRtnaC8ondo" },
  { symbol: "INTCon", name: "Intel (Ondo)", mint: "cJpUMp5R7rZ6fGeLHbHhrRuJzK9mkyKDjZqNpT3ondo" },
  { symbol: "INTUon", name: "Intuit (Ondo)", mint: "CozoH5HBTyyeYSQxHcWpGzd4Sq5XBaKzBzvTtN3ondo" },
  { symbol: "IRENon", name: "IREN (Ondo)", mint: "13QHuepdhtJ3urNsV9i1hdL8nQoca2G7ZaLzb5FYondo" },
  { symbol: "ISRGon", name: "Intuitive Surgical (Ondo)", mint: "1MGRpPrkhEsCm2GCWD3rsvEU77xTTLAzfKXeFgFondo" },
  { symbol: "ITOTon", name: "iShares Core S&P Total US Stock Market ETF (Ondo)", mint: "CPWkMURVvcnX8hGjqCTb8i5LkzV3VSvyk7SeJi8ondo" },
  { symbol: "IVVon", name: "iShares Core S&P 500 ETF (Ondo)", mint: "CqW2pd6dCPG9xKZfAsTovzDsMmAGKJSDBNcwM96ondo" },
  { symbol: "IWFon", name: "iShares Russell 1000 Growth ETF (Ondo)", mint: "dSHPFuMMjZqt7xDYGWrexXTSkdEZAiZngqymQF2ondo" },
  { symbol: "IWMon", name: "iShares Russell 2000 ETF (Ondo)", mint: "dvj2kKFSyjpnyYSYppgFdAEVfgjMEoQGi9VaV23ondo" },
  { symbol: "IWNon", name: "iShares Russell 2000 Value ETF (Ondo)", mint: "DX7g7WNjDpVzNK9CG81v7wb6ZbiNzYfkdzH2Xs5ondo" },
  { symbol: "JAAAon", name: "Janus Henderson AAA CLO ETF (Ondo)", mint: "KZtqx9BJbpcGY7vdzhqPXM3ECKChxE5YhXaDiwRondo" },
  { symbol: "JDon", name: "JD.com (Ondo)", mint: "E1aUS5nyv7kaBzdQzPVJW5zfaMgoUJpKYzdnFS2ondo" },
  { symbol: "JNJon", name: "Johnson & Johnson (Ondo)", mint: "KUXt7LzHWSQXp5eyqMZRxWjAP6yM8BUh4LRHwiwondo" },
  { symbol: "JPMon", name: "JPMorgan Chase (Ondo)", mint: "E5Gczsavxcomqf6Cw1sGCKLabL1xYD2FzKxVoB4ondo" },
  { symbol: "KLACon", name: "KLA (Ondo)", mint: "149o8ppQf9SzKCKXZ4v3dzHkwumvtQSRzSEkr29uondo" },
  { symbol: "KOon", name: "Coca-Cola (Ondo)", mint: "e6G4pfFcrdKxJuZ4YXixRFfMbpMvgXG2Mjcus71ondo" },
  { symbol: "LINon", name: "Linde (Ondo)", mint: "Edik9MoFp8LAXS9HNu2gRFyihwYqDqv4ZmNmVT9ondo" },
  { symbol: "LIon", name: "Li Auto (Ondo)", mint: "v12TwfofSbvVqQ5N5KGG4d3J8rtEi4BjGfn2apyondo" },
  { symbol: "LLYon", name: "Eli Lilly (Ondo)", mint: "eGGxZwNSfuNKRqQLKaz2hc4QkA2mau7skyxPdj7ondo" },
  { symbol: "LMTon", name: "Lockheed (Ondo)", mint: "EoReHwUnGGekbXFHLj5rbCVKiwWqu32GrETMfw4ondo" },
  { symbol: "LOWon", name: "Lowe's (Ondo)", mint: "edLdFJVVR532qhcrNTJjLAmhmyV7NsctbWVokMBondo" },
  { symbol: "LRCXon", name: "Lam Research (Ondo)", mint: "wFJoeEYpKg9oRhyJy6BWTT3J95gmXBLvoeikDQNondo" },
  { symbol: "MARAon", name: "MARA Holdings (Ondo)", mint: "ETCJUmuhs5aY62xgEVWCZ5JR8KPdeXUaJz3LuC5ondo" },
  { symbol: "MAon", name: "Mastercard (Ondo)", mint: "EsVHcyRxXFJCLMiuYLWhoDygrNe1BJGpYeZ17X7ondo" },
  { symbol: "MCDon", name: "McDonald's (Ondo)", mint: "EUbJjmDt8JA222M91bVLZs211siZ2jzbFArH9N3ondo" },
  { symbol: "MELIon", name: "MercadoLibre (Ondo)", mint: "EWwdgGshGngcMpDV34pWZRSu5bkAuiKuKTTHKQ8ondo" },
  { symbol: "METAon", name: "Meta Platforms (Ondo)", mint: "fDxs5y12E7x7jBwCKBXGqt71uJmCWsAQ3Srkte6ondo" },
  { symbol: "MPon", name: "MP Materials (Ondo)", mint: "XwFm5GiKPVTvPiEbQpdc6vJbFEpsUXRMf6TcSxnondo" },
  { symbol: "MRKon", name: "Merck (Ondo)", mint: "bn1fb8dwzafGePqNPrM8m8cbAKQiFqeEPuZkPySondo" },
  { symbol: "MRNAon", name: "Moderna (Ondo)", mint: "14VP7DvCAdBCc5XGNZkPt6zhtPzJrWWS64Koxtxyondo" },
  { symbol: "MRVLon", name: "Marvell Technology (Ondo)", mint: "FovBwhoV5KQjZCdhoM6jgXYwXLX3F8vgAfvmLH7ondo" },
  { symbol: "MSFTon", name: "Microsoft (Ondo)", mint: "FRmH6iRkMr33DLG6zVLR7EM4LojBFAuq6NtFzG6ondo" },
  { symbol: "MSTRon", name: "MicroStrategy (Ondo)", mint: "FSz4ouiqXpHuGPcpacZfTzbMjScoj5FfzHkiyu2ondo" },
  { symbol: "MTZon", name: "MasTec (Ondo)", mint: "R3ywbVQ5t8LNmjQsn2Ngv43dSqyZscQwNag9G3Eondo" },
  { symbol: "MUon", name: "Micron Technology (Ondo)", mint: "Fz9edBpaURPPzpKVRR1A8PENYDEgHqwx5D5th28ondo" },
  { symbol: "NEEon", name: "NextEra Energy (Ondo)", mint: "t7eN6cGwRMFaZvsNW2SmVwkedmHtDdrxA4ycNE5ondo" },
  { symbol: "NFLXon", name: "Netflix (Ondo)", mint: "g4KnPrxPLeeKkwvDmZFMtYQPM64eHeShbD55vK6ondo" },
  { symbol: "NIKLon", name: "Sprott Nickel Miners ETF (Ondo)", mint: "V8LRV7kWjrx6Prke9oHEHNUiR122BVtyuPciTCTondo" },
  { symbol: "NIOon", name: "NIO (Ondo)", mint: "yQ37dFiGAbzrb2FRAEhGNzRy5zFfoYGWYhAepFEondo" },
  { symbol: "NKEon", name: "Nike (Ondo)", mint: "g646pcdG2Rt5DH9WZzL7VVnVDWCCMTTrnktwE74ondo" },
  { symbol: "NOWon", name: "ServiceNow (Ondo)", mint: "G7pTVoSECz5RQWubEnTP7AC83KHUsSyoiqYR1R2ondo" },
  { symbol: "NTESon", name: "NetEase (Ondo)", mint: "YeK2TdPtGLAme3Phg4pb1GBN2YxKgX5UNVyD4asondo" },
  { symbol: "NVDAon", name: "NVIDIA (Ondo)", mint: "gEGtLTPNQ7jcg25zTetkbmF7teoDLcrfTnQfmn2ondo" },
  { symbol: "NVOon", name: "Novo Nordisk (Ondo)", mint: "GeV7S8vjP8qdYZpdGv2Xi6e7MUMCk8NAAp2z7g5ondo" },
  { symbol: "OKLOon", name: "Oklo (Ondo)", mint: "m6oDLvJT7rY7M1TxuLWP3pWmAPg2cCWDQR1NKiEondo" },
  { symbol: "ONDSon", name: "Ondas Holdings (Ondo)", mint: "7qy1j4Mechfyr6uAST3djH4vk4kiEYC2cjEytXdondo" },
  { symbol: "ONon", name: "ON Semiconductor (Ondo)", mint: "13qtwy5fZi9Przz14pzo9xqFSr8QHmLyUpUCvP1xondo" },
  { symbol: "OPENon", name: "Opendoor (Ondo)", mint: "ou1uE526v7zmUYP2qCb2LJgfXAyWAtWS9SETtr8ondo" },
  { symbol: "OPRAon", name: "Opera (Ondo)", mint: "gbHFTMkuMQUy5xrgoCBdaQ2XYvNyjWAYcnRPh9Condo" },
  { symbol: "ORCLon", name: "Oracle (Ondo)", mint: "GmDADFpfwjfzZq9MfCafMDTS69MgVjtzD7Fd9a4ondo" },
  { symbol: "OSCRon", name: "Oscar Health (Ondo)", mint: "ThwGDsXZ6iKubWuEQjmDxGwF3bUERDGbBXvcbjFondo" },
  { symbol: "OXYon", name: "Occidental Petroleum (Ondo)", mint: "1GNFMryQ6c9ZpMhgNimmsbtgYM21qnBJgRAFoNiondo" },
  { symbol: "PALLon", name: "abrdn Physical Palladium ETF (Ondo)", mint: "P7hTXnKk2d2DyqWnefp5BSroE1qjjKpKxg9SxQqondo" },
  { symbol: "PANWon", name: "Palo Alto Networks (Ondo)", mint: "M7hVQomhw4Q2D2op3HvBrZjHu9SryjNvD5haEZ1ondo" },
  { symbol: "PBRon", name: "Petrobras (Ondo)", mint: "GRciFCqJ5y2hbiD6U5mGkohY65BZTXGuGUrCqf7ondo" },
  { symbol: "PCGon", name: "PG&E (Ondo)", mint: "UP5s1srLaHDc4SwJqLPa3A48x5R7ofN3hZWxWEZondo" },
  { symbol: "PDBCon", name: "Invesco Optimum Yield Diversified Commodity ETF (Ondo)", mint: "M6agiXbNgy8Xon9ngiW4ZDPbMFcNCTMkMMkshZyondo" },
  { symbol: "PDDon", name: "PDD Holdings (Ondo)", mint: "PnjETBCLC318DRejo9cMQKAmET9PvW8AEFGWMNtondo" },
  { symbol: "PEPon", name: "PepsiCo (Ondo)", mint: "gud6b3fYekjhMG5F818BALwbg2vt4JKoow59Md9ondo" },
  { symbol: "PFEon", name: "Pfizer (Ondo)", mint: "Gwh9fPsX1qWATXy63vNaJnAFfwebWQtZaVmPko6ondo" },
  { symbol: "PGon", name: "Procter & Gamble (Ondo)", mint: "GZ8v4NdSG7CTRZqHMgNsTPRULeVi8CpdWd9wZY8ondo" },
  { symbol: "PINSon", name: "Pinterest (Ondo)", mint: "sxyg1VTSzy5zYANUK7hntNtmFAWoXGJq95AcHuVondo" },
  { symbol: "PLTRon", name: "Palantir (Ondo)", mint: "HfsnTS5qtdStwec9DfBrunRqnAMYMMz1kjv9Hu9ondo" },
  { symbol: "PLUGon", name: "Plug Power (Ondo)", mint: "TnfswqdE1jAJ8sfnf5J7kSVLEH1cfpAYZ8MWmKfondo" },
  { symbol: "PSQon", name: "ProShares Short QQQ (Ondo)", mint: "qKtU9A7ij34XmtxaSzYfxCpkgAZzzFsqnUb2kW2ondo" },
  { symbol: "PYPLon", name: "PayPal (Ondo)", mint: "hM7B3UQTTR81mS27SxDDPzBbjejmo8fnpFjzgv9ondo" },
  { symbol: "QBTSon", name: "D-Wave Quantum (Ondo)", mint: "hqJXutLF6f7DxStrWCrnZDfXzbNTZmvi3KheVi6ondo" },
  { symbol: "QCOMon", name: "Qualcomm (Ondo)", mint: "hrmX7MV5hifoaBVjnrdpz698yABxrbBNAcWtWo9ondo" },
  { symbol: "QQQon", name: "Invesco QQQ (Ondo)", mint: "HrYNm6jTQ71LoFphjVKBTdAE4uja7WsmLG8VxB8ondo" },
  { symbol: "RDDTon", name: "Reddit (Ondo)", mint: "HXFrTf9v9NdjGUTnx4sojR3Cf92hoBsQFUxKTN7ondo" },
  { symbol: "REMXon", name: "VanEck Rare Earth ETF (Ondo)", mint: "tiitb2Z1HtpB2DpVr6V7tdCFS3jmTinLeuGj9EVondo" },
  { symbol: "RGTIon", name: "Rigetti Computing (Ondo)", mint: "dwEPNKQab3iwRmjGvZPXhAmws1W5NsQGwuXwi8oondo" },
  { symbol: "RIOTon", name: "Riot Platforms (Ondo)", mint: "i6f3DvZBuLpnGSqS8x6WPeStJ7jNe5KewD6afD5ondo" },
  { symbol: "RIVNon", name: "Rivian Automotive (Ondo)", mint: "AXRsYFt7TXNQ3DcY6BkvRgPV6VsYMURyDtaeudjondo" },
  { symbol: "RTXon", name: "RTX (Ondo)", mint: "12BvLZtzjdssAycxPeBQUjukhmgQpULAvy6SroYdondo" },
  { symbol: "SBETon", name: "SharpLink Gaming (Ondo)", mint: "iLDu2jjp2i3Uqc2Vm7K7GLiUj3hR4Un49MtD7c4ondo" },
  { symbol: "SBUXon", name: "Starbucks (Ondo)", mint: "iPFqjcZQTNMNXA4kbShbMhfAVD8yr8Uq9UtXMV6ondo" },
  { symbol: "SCHWon", name: "Charles Schwab (Ondo)", mint: "cnc6M1zXLdrGR5LAQVcaJDfgezMiVWNtGQsVy1Kondo" },
  { symbol: "SGOVon", name: "iShares 0-3 Month Treasury Bond ETF (Ondo)", mint: "HjrN6ChZK2QRL6hMXayjGPLFvxhgjwKEy135VRjondo" },
  { symbol: "SHOPon", name: "Shopify (Ondo)", mint: "ivdDracs2s7jCP698dJXKSEQdVrNj9hasJL1Uq1ondo" },
  { symbol: "SLVon", name: "iShares Silver Trust (Ondo)", mint: "iy11ytbSGcUnrjE6Lfv78TFqxKyUESfku1FugS9ondo" },
  { symbol: "SMCIon", name: "Super Micro Computer (Ondo)", mint: "jLca79XzcewRuBZyaJxVxuKpUHcEix1X4CP1RP9ondo" },
  { symbol: "SNAPon", name: "Snap (Ondo)", mint: "a2cXfonVgQ6cKB4Lm8YZsPry39VZSA562bwmRSiondo" },
  { symbol: "SNOWon", name: "Snowflake (Ondo)", mint: "JmFLCBwoNvcXy6B2VqABg6m784ubkXpaEx3p7S5ondo" },
  { symbol: "SOFIon", name: "SoFi Technologies (Ondo)", mint: "mqL8yXQpeSvc7NgrAtLLPtRvUiWyLoG5RWLv16iondo" },
  { symbol: "SOUNon", name: "SoundHound AI (Ondo)", mint: "vE2qArmjto6VfeMngyGAnzp2ipLYeXsxiARDnnXondo" },
  { symbol: "SOon", name: "Southern (Ondo)", mint: "aKzjn2ZdWySSGPSSDTY2HUpcSCmemSahTXihrpyondo" },
  { symbol: "SPGIon", name: "S&P Global (Ondo)", mint: "JrTYw7A9jihX5TwpRStYviEbsYf2X2VJpZ13719ondo" },
  { symbol: "SPOTon", name: "Spotify (Ondo)", mint: "jzCvs2Pk8tDcfsFRqnEMjurgaQW4iQfEkandUR8ondo" },
  { symbol: "SPYon", name: "SPDR S&P 500 ETF (Ondo)", mint: "k18WJUULWheRkSpSquYGdNNmtuE2Vbw1hpuUi92ondo" },
  { symbol: "SQQQon", name: "ProShares UltraPro Short QQQ (Ondo)", mint: "D1tu7Fnm3cCpKyyPXrqm5GXShPqMj7a2SEjjq9fondo" },
  { symbol: "TCOMon", name: "Trip.com Group (Ondo)", mint: "9PMjLqd8zPdKkJUXarnit5t7tPL3cCscwHzy7ATondo" },
  { symbol: "TIPon", name: "iShares TIPS Bond ETF (Ondo)", mint: "k6BPp2Xmf2TYgrZiUyWfUoZBKeqaDbvPoAVgSx2ondo" },
  { symbol: "TLNon", name: "Talen Energy (Ondo)", mint: "RTb54gpqAx6RpLAHRGnqQ3ciQ845CHqhg21ZzEJondo" },
  { symbol: "TLTon", name: "iShares 20+ Year Treasury Bond ETF (Ondo)", mint: "KaSLSWByKy6b9FrCYXPEJoHmLpuFZtTCJk1F1Z9ondo" },
  { symbol: "TMOon", name: "Thermo Fisher Scientific (Ondo)", mint: "T699bgtXQw4CJ59rQ4VzLsupVQUzoL5RmuhHnKrondo" },
  { symbol: "TMUSon", name: "T-Mobile US (Ondo)", mint: "pDY4GPJfZcNETPG7myXeafQfgJqqVkn81bMYDyfondo" },
  { symbol: "TMon", name: "Toyota (Ondo)", mint: "kbmF7ERJWMaaDswMprrH9gHSLya5D2RMBNgKqg3ondo" },
  { symbol: "TQQQon", name: "ProShares UltraPro QQQ (Ondo)", mint: "14W1itEkV7k1W819mLSknFTaMmkCtPokbF2tRkPUondo" },
  { symbol: "TSLAon", name: "Tesla (Ondo)", mint: "KeGv7bsfR4MheC1CkmnAVceoApjrkvBhHYjWb67ondo" },
  { symbol: "TSMon", name: "Taiwan Semiconductor (Ondo)", mint: "keybg184d4vyXeQdFqs4o99YsMg7xBthxTJ6Ky3ondo" },
  { symbol: "TXNon", name: "Texas Instruments (Ondo)", mint: "81xLFvCzFaUM3KDxSHC75pXu3RPCeSeCbmGBY8aondo" },
  { symbol: "Ton", name: "AT&T (Ondo)", mint: "WKMZummev5UcXz5nNKQZvTD6QjNSM2X58uwmDReondo" },
  { symbol: "UBERon", name: "Uber (Ondo)", mint: "KJNeFW3kk3ycPjXpC6cbuyckjeYHacc2ekhtAi5ondo" },
  { symbol: "UNHon", name: "UnitedHealth (Ondo)", mint: "kPBGL8vAwKN3UGmr9cjkM2dU79SC3nzTC9yu7F8ondo" },
  { symbol: "USFRon", name: "WisdomTree Floating Rate Treasury Fund (Ondo)", mint: "o6U1Sm6Vd7EofMyCrL28mrp2QLzgYGgjveHiEQ5ondo" },
  { symbol: "USOon", name: "United States Oil Fund (Ondo)", mint: "rpydAzWdCy85HEmoQkH5PVxYtDYQWjmLxgHHadxondo" },
  { symbol: "Von", name: "Visa (Ondo)", mint: "kxEW4oJL75K37VeXaZF1ynbHQATQwhECQKN1374ondo" },
  { symbol: "VRTon", name: "Vertiv (Ondo)", mint: "MkN2TZSYTFBdMRLf9EVcfhstTwnazH8knd9hpepondo" },
  { symbol: "VSTon", name: "Vistra (Ondo)", mint: "h6MW8GFpfzxFa1JNn6hZNnBF3t4fj9SHAXKy6LXondo" },
  { symbol: "VTIon", name: "Vanguard Total Stock Market ETF (Ondo)", mint: "jCCU4GwukjNxAXJowG2S4KCrr5g6YyUB61WHYvGondo" },
  { symbol: "VTVon", name: "Vanguard Value ETF (Ondo)", mint: "KuiYLPVq65qixD9TgvxBC576C4gG6vVTCdbh2zFondo" },
  { symbol: "VZon", name: "Verizon (Ondo)", mint: "igu1coP6n3GPaWmbd8J9Z7UAyLpV254uQFFNfydondo" },
  { symbol: "WFCon", name: "Wells Fargo (Ondo)", mint: "L6ZE5qCpVVSqLePz64CrwkgyWoPF9M7tB8BeFH4ondo" },
  { symbol: "WMTon", name: "Walmart (Ondo)", mint: "LZddqAqKqJW9oMZSjTxCUmbmzBRQtv9gMkD9hZ3ondo" },
  { symbol: "WULFon", name: "Terawulf (Ondo)", mint: "exYfSJt6Fgfhfnp3bAD4roYy97hLF9npjYaLyEXondo" },
  { symbol: "XOMon", name: "Exxon Mobil (Ondo)", mint: "qCYD74QnXzd9pzv6pGHQKJVwoibL6sNcPQDnpDiondo" },
  { symbol: "XYZon", name: "Block (Ondo)", mint: "BWxe2FVciUbwrCUZQPUKiREBh5LmVa5AiUqNLAkondo" },
];

async function seed(): Promise<void> {
  console.log("Seeding xStocks (63 tokens, decimals=8)...");
  let xCount = 0;
  for (const token of XSTOCKS) {
    await prisma.tradeableAsset.upsert({
      where: { symbol: token.symbol },
      update: { name: token.name, mint: token.mint, decimals: 8, isActive: true },
      create: { symbol: token.symbol, name: token.name, mint: token.mint, decimals: 8 },
    });
    xCount++;
  }
  console.log(`  Upserted ${xCount} xStock tokens`);

  console.log("Seeding Ondo GM tokens (203 tokens, decimals=9)...");
  let oCount = 0;
  for (const token of ONDO_TOKENS) {
    await prisma.tradeableAsset.upsert({
      where: { symbol: token.symbol },
      update: { name: token.name, mint: token.mint, decimals: 9, isActive: true },
      create: { symbol: token.symbol, name: token.name, mint: token.mint, decimals: 9 },
    });
    oCount++;
  }
  console.log(`  Upserted ${oCount} Ondo GM tokens`);
  console.log(`Total: ${xCount + oCount} stock tokens seeded`);
}

seed()
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
