// Constants
export {
  VAULT_PROGRAM_ID,
  PROGRAM_AUTHORITY,
  DISC_INITIALIZE,
  DISC_ADD_OWNER,
  DISC_REMOVE_OWNER,
  DISC_ADD_OPERATOR,
  DISC_REMOVE_OPERATOR,
  DISC_SET_SHARE_PRICE,
  DISC_EXECUTE,
  DISC_UPDATE_FEES,
  DISC_COLLECT_FEES,
  DISC_DEPOSIT_WITH_PRICE,
  DISC_REQUEST_DEPOSIT,
  DISC_FULFILL_DEPOSIT,
  DISC_WITHDRAW_WITH_PRICE,
  DISC_REQUEST_WITHDRAW,
  DISC_FULFILL_WITHDRAW,
  DISC_INITIALIZE_FACTORY,
  DISC_ADD_FACTORY_ADMIN,
  DISC_REMOVE_FACTORY_ADMIN,
  DISC_TRANSFER_FACTORY_OWNERSHIP,
  DISC_ACCEPT_FACTORY_OWNERSHIP,
  DISC_PAUSE_FACTORY,
  DISC_UNPAUSE_FACTORY,
  DISC_TRANSFER_VAULT_ADMIN,
  DISC_ACCEPT_VAULT_ADMIN,
  DISC_PAUSE_VAULT,
  DISC_UNPAUSE_VAULT,
  DISC_CANCEL_DEPOSIT,
  DISC_CANCEL_WITHDRAW,
  VAULT_DISCRIMINATOR,
  PENDING_DEPOSIT_DISCRIMINATOR,
  PENDING_WITHDRAW_DISCRIMINATOR,
  FACTORY_DISCRIMINATOR,
  VAULT_STATE_SIZE,
  PENDING_DEPOSIT_SIZE,
  PENDING_WITHDRAW_SIZE,
  FACTORY_STATE_SIZE,
  MAX_OWNERS,
  MAX_OPERATORS,
  MAX_FACTORY_ADMINS,
  SPL_TOKEN_PROGRAM_ID,
  TOKEN_2022_PROGRAM_ID,
  SYSTEM_PROGRAM_ID,
  CLOCK_SYSVAR_ID,
  PENDING_EXPIRY_SECONDS,
  BPS_DENOMINATOR,
  SECONDS_PER_YEAR,
  MAX_ENTRY_EXIT_FEE_BPS,
  MAX_MANAGEMENT_FEE_BPS,
  MAX_PERFORMANCE_FEE_BPS,
} from "./constants.js";

// PDA derivation
export {
  findFactoryPda,
  findVaultStatePda,
  findShareMintPda,
  findPendingDepositPda,
  findPendingWithdrawPda,
} from "./pda.js";

// State deserialization
export {
  deserializeVaultState,
  deserializePendingDeposit,
  deserializePendingWithdraw,
  deserializeFactoryState,
} from "./state/index.js";
export type {
  VaultState,
  PendingDeposit,
  PendingWithdraw,
  FactoryState,
} from "./state/index.js";

// Instruction builders
export {
  createInitializeInstruction,
  createAddOperatorInstruction,
  createRemoveOperatorInstruction,
  createAddOwnerInstruction,
  createRemoveOwnerInstruction,
  createSetSharePriceInstruction,
  createExecuteInstruction,
  createUpdateFeesInstruction,
  createCollectFeesInstruction,
  createDepositWithPriceInstruction,
  createRequestDepositInstruction,
  createFulfillDepositInstruction,
  createWithdrawWithPriceInstruction,
  createRequestWithdrawInstruction,
  createFulfillWithdrawInstruction,
  createInitializeFactoryInstruction,
  createTransferFactoryOwnershipInstruction,
  createAcceptFactoryOwnershipInstruction,
  createAddFactoryAdminInstruction,
  createRemoveFactoryAdminInstruction,
  createPauseFactoryInstruction,
  createUnpauseFactoryInstruction,
  createTransferVaultAdminInstruction,
  createAcceptVaultAdminInstruction,
  createPauseVaultInstruction,
  createUnpauseVaultInstruction,
  createCancelDepositInstruction,
  createCancelWithdrawInstruction,
} from "./instructions/index.js";
export type {
  InitializeParams,
  AddOperatorParams,
  RemoveOperatorParams,
  AddOwnerParams,
  RemoveOwnerParams,
  SetSharePriceParams,
  ExecuteParams,
  UpdateFeesParams,
  CollectFeesParams,
  DepositWithPriceParams,
  RequestDepositParams,
  FulfillDepositParams,
  WithdrawWithPriceParams,
  RequestWithdrawParams,
  FulfillWithdrawParams,
  InitializeFactoryParams,
  TransferFactoryOwnershipParams,
  AcceptFactoryOwnershipParams,
  AddFactoryAdminParams,
  RemoveFactoryAdminParams,
  PauseFactoryParams,
  UnpauseFactoryParams,
  TransferVaultAdminParams,
  AcceptVaultAdminParams,
  PauseVaultParams,
  UnpauseVaultParams,
  CancelDepositParams,
  CancelWithdrawParams,
} from "./instructions/index.js";

// Fee math
export {
  applyFee,
  managementFeeShares,
  performanceFeeShares,
  validateFeeBps,
} from "./fees.js";

// Errors
export { VaultErrorCode, parseVaultError } from "./errors.js";
